// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// // ...
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbFaeeFAc64weptmovj0JUngWrZiCbJ2M',
    appId: '1:179601431762:web:644297e877d01cb7ce210b',
    messagingSenderId: '179601431762',
    projectId: 'final-project-sanbercode-342b7',
    authDomain: 'final-project-sanbercode-342b7.firebaseapp.com',
    storageBucket: 'final-project-sanbercode-342b7.appspot.com',
    measurementId: 'G-00LD4E1863',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcJUIuBzEIwovmWc47trm-DvOiIKC8nBQ',
    appId: '1:179601431762:android:d7c433a789909662ce210b',
    messagingSenderId: '179601431762',
    projectId: 'final-project-sanbercode-342b7',
    storageBucket: 'final-project-sanbercode-342b7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCg-4oEn__OfwIaHydFELyWURRHOUeCnJE',
    appId: '1:179601431762:ios:6cd0b556d6159dd8ce210b',
    messagingSenderId: '179601431762',
    projectId: 'final-project-sanbercode-342b7',
    storageBucket: 'final-project-sanbercode-342b7.appspot.com',
    iosClientId: '179601431762-hipb6iods7cmh3df70ha018ea7qar4m2.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalProject',
  );
}
